language: java

branches:

  only:
    - master
    - release
    - develop
    - feature

jenkins:
  pipeline_jenkinsfile: aurea-central-jervis/pipelines/SaaS
  collect:
    artifacts: 'target/*.jar'
    junit: '**/*.xml'

services:
    petclinc:
      docker_image:
        path: .
        name: registry2.swarm.devfactory.com/aurea/central/jervis/petclinic
        